### ISSUE TITLE
App crashes on record button.

### ISSUE THREAD

**Issue by nm17** [Xmader/google-recorder#1]
System info + stacktrace: 
https://gist.github.com/nm17/a85ad5de74edaeaf4e2da6ffbddbafbe

Video: https://youtu.be/V5-ugKyviN0

Using an already built apk from https://github.com/Xmader/google-recorder/releases/tag/v1.1.284933798

Links to people having the same issue:
  - https://www.reddit.com/r/Mi9T/comments/e6io5g/google_recorder_for_the_mi_9tpro/
  - https://www.reddit.com/r/Mi9T/comments/e0xs1z/google_recorder_app_crashes_on_mi_9t/
  - https://www.reddit.com/r/Xiaomi/comments/dibygz/google_recorder_crashing_on_mi_9/

**Comment by nm17** [comment]
@Xmader same error on https://github.com/Xmader/google-recorder/releases/tag/v1.1.283481728

**Comment by nm17** [comment]
Latest version crashes at start ([v1.1.289058594](https://github.com/Xmader/google-recorder/releases/tag/v1.1.289058594)):
```
java.lang.RuntimeException: Unable to create application com.google.android.apps.recorder.ui.application.RecorderApplication: java.lang.IllegalStateException: Cannot start Recorder on unsupported device
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6545)
	at android.app.ActivityThread.access$1400(ActivityThread.java:220)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalStateException: Cannot start Recorder on unsupported device
	at com.google.android.apps.recorder.ui.application.RecorderApplication.onCreate(PG:13)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6540)
	... 8 more
```

**Comment by Xmader** [comment]
> `java.lang.RuntimeException: Unable to create application com.google.android.apps.recorder.ui.application.RecorderApplication: java.lang.IllegalStateException: Cannot start Recorder on unsupported device`

It is the original error message without the patch.

**Comment by Xmader** [comment]
The [release artifact file](https://github.com/Xmader/google-recorder/releases/tag/v1.1.289058594) is updated.
